<a href="https://colab.research.google.com/github/bhagyasree2004/Python_Module/blob/main/pandas%26numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY

import numpy as np
a=np.array([1,2,3,4], dtype=float)
print(a)

[1. 2. 3. 4.]


Dimensions of numpy


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
len(b)
b.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
c=np.array([1,2,3])
print(c)

[1 2 3]


In [ ]:
c=np.array([1,2,3,5,6,7,8])
print(c)
len(c)

[1 2 3 5 6 7 8]


7

In [ ]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d)
type(d)
np.ndim(d)
d.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [ ]:
e=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(e)
e.ndim

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


4

Shape of numpy array


In [ ]:
#get a shape of numpy array
a.shape

(4,)

In [ ]:
b.shape

(3, 3)

In [ ]:
c.shape

(7,)

In [ ]:
d.shape

(1, 3, 3)

In [ ]:
e.shape

(1, 1, 3, 3)

Accessing/changing specific element


In [ ]:
z=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
z[0,2]=40
z

array([[ 1,  2, 40,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
z[0,4]=50
print(z)

[[ 1  2  3 40 50  6  7]
 [ 8  9 10 11 12 13 14]]


Zeros & ones method

In [ ]:
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((3,3),dtype='str')

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [ ]:
varb=30
np.full((3,3,),varb,dtype='float')

array([[30., 30., 30.],
       [30., 30., 30.],
       [30., 30., 30.]])

In [ ]:
np.random.rand(4,4)

array([[0.11910003, 0.15836777, 0.26572676, 0.32302677],
       [0.8698741 , 0.45649332, 0.09771737, 0.5679839 ],
       [0.51557229, 0.1456239 , 0.57766708, 0.10030832],
       [0.87789372, 0.35148186, 0.97931408, 0.42882847]])

In [ ]:
np.random.randint(0, 10, size=(4,4))

array([[3, 2, 2, 0],
       [8, 4, 5, 6],
       [4, 9, 9, 2],
       [0, 1, 3, 9]])

In [ ]:
np.random.randint(-1, 0, size=(4,4))

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [ ]:
np.random.randint(-10, -1, size=(4,4))

array([[ -2,  -2,  -8,  -2],
       [ -5,  -8,  -6,  -2],
       [ -3,  -6,  -5,  -7],
       [ -9,  -5, -10,  -8]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity((3),dtype='int')

<function shape at 0x78ec7e575730>

In [ ]:
#extract all the first 3 rows of the last 5th column in a given 2d array 'a'

a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)


a[:3,4:5]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 5],
       [10],
       [15]])

In [ ]:
a[:3,4]

array([ 5, 10, 15])

In [ ]:
a[0:3,-5:-1]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [ ]:
#Q. give a positive no 'n' greater than 2 create a numpy array of size(n*n) with all zeroes and ones such that ones make a sahape

import numpy as np

def create_shape_array(n):
    arr = np.zeros((n, n), dtype=int)
    mid = n // 2

    arr[mid, :] = 1
    arr[:, mid] = 1

    return arr

n = 5
result = create_shape_array(n)
print(result)


arr=np.zeros((n,n),dtype='int')





[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [ ]:
arr=np.zeros((5,5),dtype='int')

mid=n//2

arr[mid, :] = 1
arr
arr[:, mid] = 1
arr

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [ ]:
#diagonal elements should be zeros and one
arr=np.zeros((5,5),dtype='int')


In [ ]:
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Arthimetic operations

In [ ]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a+2

array([3, 4, 5, 6, 7])

In [ ]:
a**3

array([  1,   8,  27,  64, 125])

In [ ]:
a-3

array([-2, -1,  0,  1,  2])

In [ ]:
a*3

array([ 3,  6,  9, 12, 15])

In [ ]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [ ]:
a//3

array([0, 0, 1, 1, 1])

In [ ]:
a%3

array([1, 2, 0, 1, 2])

In [ ]:
a.min()

np.int64(1)

In [ ]:
np.min(a)

np.int64(1)

In [ ]:
a.max()

np.int64(5)

In [ ]:
np.max(a)

np.int64(5)

In [ ]:
np.average(a)

np.float64(3.0)

In [ ]:
a.mean()

np.float64(3.0)

In [ ]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b.ndim

2

In [ ]:
np.max(b)

np.int64(10)

In [ ]:
np.min(1)

np.int64(1)

In [ ]:
np.max(b,axis=1)

array([ 5, 10])

In [ ]:
np.max(b,axis=0)

array([ 6,  7,  8,  9, 10])

PYTHON


In [ ]:
#pandas

import pandas as pd
import numpy as np
df=pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes


In [ ]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No


In [ ]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges
count,7043.000000,7043.000000,7043.000000
mean,0.162147,32.371149,64.761692
std,0.368612,24.559481,30.090047
min,0.000000,0.000000,18.250000
25%,0.000000,9.000000,35.500000
50%,0.000000,29.000000,70.350000
75%,0.000000,55.000000,89.850000
max,1.000000,72.000000,118.750000


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [ ]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
#transpose
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU,9305-CDSKC,1452-KIOVK,6713-OKOMC,7892-POOKP,6388-TABGU,...,9767-FFLEM,0639-TSIQW,8456-QDAVC,7750-EYXWZ,2569-WGERO,6840-RESVB,2234-XADUH,4801-JZAZL,8361-LTMKD,3186-AJIEK
gender,Female,Male,Male,Male,Female,Female,Male,Female,Female,Male,...,Male,Female,Male,Female,Female,Male,Female,Female,Male,Male
SeniorCitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Partner,Yes,No,No,No,No,No,No,No,Yes,No,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No
Dependents,No,No,No,No,No,No,Yes,No,No,Yes,...,No,No,No,No,No,Yes,Yes,Yes,No,No
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
PhoneService,No,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Yes,...,Yes,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Yes
MultipleLines,No phone service,No,No,No phone service,No,Yes,Yes,No phone service,Yes,No,...,No,Yes,No,No phone service,No,Yes,Yes,No phone service,Yes,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic,Fiber optic,Fiber optic,DSL,Fiber optic,DSL,...,Fiber optic,Fiber optic,Fiber optic,DSL,No,DSL,Fiber optic,DSL,Fiber optic,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No,No,No,Yes,No,Yes,...,No,Yes,No,No,No internet service,Yes,No,Yes,No,Yes


In [ ]:
#sort your df based on age
df.sort_values('MonthlyCharges')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3719,6823-SIDFQ,Male,0,No,No,28,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),18.25,534.7,No
1529,9764-REAFF,Female,0,Yes,No,59,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),18.40,1057.85,No
6652,0827-ITJPH,Male,0,No,No,36,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),18.55,689,No
1156,0621-CXBKL,Female,0,No,No,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,18.70,1005.7,No
6906,9945-PSVIP,Female,0,Yes,Yes,25,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,18.70,383.65,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5127,8199-ZLLSA,Male,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),118.35,7804.15,Yes
3894,5989-AXPUC,Female,0,Yes,No,68,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Mailed check,118.60,7990.05,No
4804,5734-EJKXG,Female,0,No,No,61,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,118.60,7365.7,No
2115,8984-HPEMB,Female,0,No,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.65,8477.6,No


In [ ]:
new_df=df.sort_values('MonthlyCharges')
new_df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3719,6823-SIDFQ,Male,0,No,No,28,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),18.25,534.7,No
1529,9764-REAFF,Female,0,Yes,No,59,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),18.40,1057.85,No
6652,0827-ITJPH,Male,0,No,No,36,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),18.55,689,No
1156,0621-CXBKL,Female,0,No,No,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,18.70,1005.7,No
6906,9945-PSVIP,Female,0,Yes,Yes,25,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,18.70,383.65,No


In [ ]:
df['MonthlyCharges']

,MonthlyCharges
0,29.85
1,56.95
2,53.85
3,42.30
4,70.70
...,...
7038,84.80
7039,103.20
7040,29.60
7041,74.40


In [ ]:
df['MonthlyCharges']+100



,MonthlyCharges
0,129.85
1,156.95
2,153.85
3,142.30
4,170.70
...,...
7038,184.80
7039,203.20
7040,129.60
7041,174.40


adding new columns

In [ ]:
df['MonthlyCharges-']=df['MonthlyCharges']+100
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MonthlyCharges-
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,129.85
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.5,No,156.95
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,153.85
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,142.30
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,170.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,184.80
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,203.20
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,129.60
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,174.40


In [ ]:
df['Random column']='Good day'
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MonthlyCharges-,Random column
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,129.85,Good day
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,No,156.95,Good day
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,153.85,Good day
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,142.30,Good day
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,170.70,Good day


How to acces rows


In [ ]:
#how to access rows
df[20:25]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MonthlyCharges-,Random column
20,8779-QRDMV,Male,1,No,No,1,No,No phone service,DSL,No,...,No,Yes,Month-to-month,Yes,Electronic check,39.65,39.65,Yes,139.65,Good day
21,1680-VDCWW,Male,0,Yes,No,12,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Bank transfer (automatic),19.80,202.25,No,119.80,Good day
22,1066-JKSGK,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.15,20.15,Yes,120.15,Good day
23,3638-WEABW,Female,0,Yes,No,58,Yes,Yes,DSL,No,...,No,No,Two year,Yes,Credit card (automatic),59.90,3505.1,No,159.90,Good day
24,6322-HRPFA,Male,0,Yes,Yes,49,Yes,No,DSL,Yes,...,No,No,Month-to-month,No,Credit card (automatic),59.60,2970.3,No,159.60,Good day


where clause where your age>0


In [ ]:
#where clause where your age>50
df[df.MonthlyCharges>100]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MonthlyCharges-,Random column
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,204.80,Good day
12,8091-TTVAX,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.1,No,200.35,Good day
13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,203.70,Good day
14,5129-JLPIS,Male,0,No,No,25,Yes,No,Fiber optic,Yes,...,Yes,Yes,Month-to-month,Yes,Electronic check,105.50,2686.05,No,205.50,Good day
15,3655-SNQYZ,Female,0,Yes,Yes,69,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Two year,No,Credit card (automatic),113.25,7895.15,No,213.25,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7022,7203-OYKCT,Male,0,No,No,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Electronic check,104.95,7544.3,No,204.95,Good day
7023,1035-IPQPU,Female,1,Yes,No,63,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,103.50,6479.4,No,203.50,Good day
7034,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes,202.95,Good day
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,203.20,Good day


In [ ]:
MonthlyCharges_100=df[df.MonthlyCharges>100]
len(MonthlyCharges_100)

902

In [ ]:
len(df)

7043

In [ ]:
#fill null values

df['MonthlyCharges'].fillna(10)


,MonthlyCharges
0,29.85
1,56.95
2,53.85
3,42.30
4,70.70
...,...
7038,84.80
7039,103.20
7040,29.60
7041,74.40


In [ ]:
#reembe or delete one of the column

new_df.pop('Partner')

,Partner
3719,No
1529,Yes
6652,No
1156,No
6906,Yes
...,...
5127,No
3894,Yes
4804,No
2115,No


In [ ]:
new_df

,customerID,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3719,6823-SIDFQ,Male,0,No,28,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),18.25,534.7,No
1529,9764-REAFF,Female,0,No,59,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),18.40,1057.85,No
6652,0827-ITJPH,Male,0,No,36,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),18.55,689,No
1156,0621-CXBKL,Female,0,No,53,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,18.70,1005.7,No
6906,9945-PSVIP,Female,0,Yes,25,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,18.70,383.65,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5127,8199-ZLLSA,Male,0,No,67,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),118.35,7804.15,Yes
3894,5989-AXPUC,Female,0,No,68,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Mailed check,118.60,7990.05,No
4804,5734-EJKXG,Female,0,No,61,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,118.60,7365.7,No
2115,8984-HPEMB,Female,0,No,71,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.65,8477.6,No


In [ ]:
new_df.drop(columns='customerID')

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3719,Male,0,No,28,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),18.25,534.7,No
1529,Female,0,No,59,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),18.40,1057.85,No
6652,Male,0,No,36,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),18.55,689,No
1156,Female,0,No,53,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,18.70,1005.7,No
6906,Female,0,Yes,25,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,18.70,383.65,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5127,Male,0,No,67,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),118.35,7804.15,Yes
3894,Female,0,No,68,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Mailed check,118.60,7990.05,No
4804,Female,0,No,61,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,118.60,7365.7,No
2115,Female,0,No,71,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,118.65,8477.6,No


In [ ]:
#apply methods

df['MonthlyCharges']


,MonthlyCharges
0,29.85
1,56.95
2,53.85
3,42.30
4,70.70
...,...
7038,84.80
7039,103.20
7040,29.60
7041,74.40


In [ ]:
df['MonthlyCharges'].apply(np.sqrt)

,MonthlyCharges
0,5.463515
1,7.546522
2,7.338256
3,6.503845
4,8.408329
...,...
7038,9.208692
7039,10.158740
7040,5.440588
7041,8.625543


In [ ]:
df['sqrt']=df['MonthlyCharges'].apply(np.sqrt)

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,MonthlyCharges-,Random column,sqrt
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,129.85,Good day,5.463515
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,One year,No,Mailed check,56.95,1889.5,No,156.95,Good day,7.546522
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,153.85,Good day,7.338256
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,142.30,Good day,6.503845
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,170.70,Good day,8.408329


In [ ]:
#how to drop null values

df['MonthlyCharges'].dropna()


,MonthlyCharges
0,29.85
1,56.95
2,53.85
3,42.30
4,70.70
...,...
7038,84.80
7039,103.20
7040,29.60
7041,74.40


In [ ]:
#concat and merge
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                  'B':['B0','B1','B2','B3'],
                  'D':['D0','D1','D2','D3']},index=[0,1,2,3])

df1


,A,B,D
0,A0,B0,D0
1,A1,B1,D1
2,A2,B2,D2
3,A3,B3,D3


In [ ]:
#concat and merge
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                  'B':['B4','B5','B6','B7'],
                  'c':['C4','C5','C6','C7'],
                  'D':['D4','D5','D6','D7']},index=[4,5,6,7])

df2

,A,B,c,D
4,A4,B4,C4,D4
5,A5,B5,C5,D5
6,A6,B6,C6,D6
7,A7,B7,C7,D7


In [ ]:
pd.concat([df1, df2])

,A,B,c,D
0,A4,B0,C0,D0
1,A5,B1,C1,D1
2,A6,B2,C2,D2
3,A7,B3,C3,D3
4,A4,B4,C4,D4
5,A5,B5,C5,D5
6,A6,B6,C6,D6
7,A7,B7,C7,D7


In [ ]:
#merge

df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                  'C':['C4','C1','C2','C3'],
                  'D':['D0','D1','D2','D3']},index=[0,1,2,3])

In [ ]:
df2=pd.DataFrame({'E':['E4','E5','E6','E7'],
                  'F':['F4','F5','F6','F7'],
                  'C':['C4','C1','C2','C3'],
                  'G':['G4','G5','G6','G7']},index=[4,5,6,7])

df2

,E,F,C,G
4,E4,F4,C4,G4
5,E5,F5,C1,G5
6,E6,F6,C2,G6
7,E7,F7,C3,G7


In [ ]:
df1

,A,B,C,D
0,A0,B0,C4,D0
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3


In [ ]:
merge_df=pd.merge(df1,df2,on='C' ,how='inner')



In [ ]:
merge_df

,A,B,C,D,E,F,G
0,A0,B0,C4,D0,E4,F4,G4
1,A1,B1,C1,D1,E5,F5,G5
2,A2,B2,C2,D2,E6,F6,G6
3,A3,B3,C3,D3,E7,F7,G7


In [ ]:
df1=pd.DataFrame({'A':['A']})

In [ ]:
merge_df=pd.merge(df1,df2,on='C' ,how='inner')

In [ ]:
merge_df

,A,C,E,F,G
0,A0,C4,E4,F4,G4


In [ ]:
import pandas as pd

# DataFrames
df1 = pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C4','C1','C2','C3'],
    'D':['D0','D1','D2','D3']
})

df2 = pd.DataFrame({
    'E':['E4','E5','E6','E7'],
    'F':['F4','F5','F6','F7'],
    'C':['C4','C1','C2','C3'],
    'G':['G4','G5','G6','G7']
})

# Merge
merge_df = pd.merge(df1, df2, on='C', how='inner')

print(merge_df)

    A   B   C   D   E   F   G
0  A0  B0  C4  D0  E4  F4  G4
1  A1  B1  C1  D1  E5  F5  G5
2  A2  B2  C2  D2  E6  F6  G6
3  A3  B3  C3  D3  E7  F7  G7


In [ ]:
#loc and iloc
#loc get a rows or column with particular labels
#iloc get rows or columns ith location

In [ ]:
import pandas as pd
import numpy as np

s=pd.Series(list("abcdef"),index=[49,48,47,0,1,2])

In [ ]:
s

,0
49,a
48,b
47,c
0,d
1,e
2,f


In [ ]:
s.loc[0]

'd'

In [ ]:
s.iloc[0]

'a'

In [ ]:
s.iloc[3]

'd'

In [ ]:
s.loc[0:1]

,0
0,d
1,e


In [ ]:
s.iloc[0:1]

,0
49,a


In [ ]:
S = s.sort_index()

In [ ]:
S

,0
0,d
1,e
2,f
47,c
48,b
49,a


In [ ]:
S.iloc[0]

'd'

In [ ]:
S.loc[0]

'd'